<?php $errors = $_SESSION['order_errors'] ?? []; $oldInput = $_SESSION['order_old_input'] ?? []; unset($_SESSION['order_errors'], $_SESSION['order_old_input']); ?>
<main class="py-5"><div class="container"><div class="row justify-content-center"><div class="col-lg-8"><section class="card border-0 shadow-sm"><div class="card-body p-4 p-md-5">
<span class="badge bg-primary-subtle text-primary">Étape finale</span><h1 class="h2 text-primary mt-3">Commander un menu</h1><p class="text-muted">Le prix définitif, la remise et le stock sont vérifiés côté serveur lors de la validation.</p>
<?php if (isset($errors['general'])): ?><div class="alert alert-danger"><?= $escape($errors['general']) ?></div><?php endif; ?>
<form method="post" action="/orders" class="row g-3"><input type="hidden" name="csrf_token" value="<?= $escape($csrfToken) ?>">
<div class="col-12"><label class="form-label" for="menu_id">Menu</label><select class="form-select <?= isset($errors['menu_id']) ? 'is-invalid' : '' ?>" id="menu_id" name="menu_id" required><option value="">Sélectionnez un menu</option><?php foreach ($menus as $menu): $isSelected = (int) ($oldInput['menu_id'] ?? $selectedMenuId) === $menu->getId(); ?><option value="<?= $menu->getId() ?>" <?= $isSelected ? 'selected' : '' ?>><?= $escape($menu->getTitle()) ?> — <?= number_format($menu->getBasePrice(), 2, ',', ' ') ?> € / personne (minimum <?= $menu->getMinPeople() ?>)</option><?php endforeach; ?></select><?php if (isset($errors['menu_id'])): ?><div class="invalid-feedback"><?= $escape($errors['menu_id']) ?></div><?php endif; ?></div>
<div class="col-md-4"><label class="form-label" for="number_of_people">Nombre de personnes</label><input class="form-control <?= isset($errors['number_of_people']) ? 'is-invalid' : '' ?>" id="number_of_people" name="number_of_people" type="number" min="1" value="<?= $escape($oldInput['number_of_people'] ?? '') ?>" required></div>
<div class="col-md-4"><label class="form-label" for="delivery_date">Date</label><input class="form-control <?= isset($errors['delivery_date']) ? 'is-invalid' : '' ?>" id="delivery_date" name="delivery_date" type="date" min="<?= date('Y-m-d') ?>" value="<?= $escape($oldInput['delivery_date'] ?? '') ?>" required></div>
<div class="col-md-4"><label class="form-label" for="delivery_time">Heure</label><input class="form-control <?= isset($errors['delivery_time']) ? 'is-invalid' : '' ?>" id="delivery_time" name="delivery_time" type="time" value="<?= $escape($oldInput['delivery_time'] ?? '') ?>" required></div>
<div class="col-12"><label class="form-label" for="delivery_address">Adresse de prestation</label><textarea class="form-control <?= isset($errors['delivery_address']) ? 'is-invalid' : '' ?>" id="delivery_address" name="delivery_address" required><?= $escape($oldInput['delivery_address'] ?? '') ?></textarea></div>
<div class="col-12"><button class="btn btn-primary" type="submit">Valider la commande</button></div>
</form></div></section></div></div></div></main>
